---@class debuglib.DebugInfo
---@field name            string
---@field namewhat        string
---@field source          string
---@field short_src       string
---@field linedefined     integer
---@field lastlinedefined integer
---@field what            string
---@field currentline     integer
---@field istailcall      boolean
---@field nups            integer
---@field nparams         integer
---@field isvararg        boolean
---@field func            function
---@field ftransfer       integer
---@field ntransfer       integer
---@field activelines     table

---@alias debuglib.InfoWhat
---|+"n"     # `name`, `namewhat`
---|+"S"     # `source`, `short_src`, `linedefined`, `lastlinedefined`, `what`
---|+"l"     # `currentline`
---|+"t"     # `istailcall`
---|+"u"     # `nups`, `nparams`, `isvararg`
---|+"f"     # `func`
---|+"r"     # `ftransfer`, `ntransfer`
---|+"L"     # `activelines`
---| string

---Returns debug information about a function.
---
---Pass either a function or a stack level as `f`.
---Level 0 is the `debug.getinfo` call itself, level 1 is its caller, and so on.
---For out-of-range stack levels, this can return nil.
---@overload fun(f: function, what?: debuglib.InfoWhat): debuglib.DebugInfo
---@overload fun(f: 0, what?: debuglib.InfoWhat): debuglib.DebugInfo
---@overload fun(f: integer, what?: debuglib.InfoWhat): debuglib.DebugInfo?
---@overload fun(thread: thread, f: function, what?: debuglib.InfoWhat): debuglib.DebugInfo
---@overload fun(thread: thread, f: 0, what?: debuglib.InfoWhat): debuglib.DebugInfo
---@param thread thread
---
---Takes either a function or a number representing the stack level as an argument. Stack level 0 always corresponds to the debug.getinfo call, 1 would be the function calling debug.getinfo in most cases, and so on.
--- Returns useful information about that function in a table.
---@param f integer|function
---
--- * `f` - Populates the func field.
--- * `l` - Populates the currentline field.
--- * `L` - Populates the activelines field.
--- * `n` - Populates the name and namewhat fields - only works if stack level is passed rather than function pointer.
--- * `S` - Populates the location fields (lastlinedefined, linedefined, short_src, source and what).
--- * `u` - Populates the argument and upvalue fields (isvararg, nparams, nups).
--- * `>` - Causes this function to use the last argument to get the data from.
---@param what? debuglib.InfoWhat
---
---Function to use. (Only used by the `>` field)
---@return debuglib.DebugInfo?
---
--- A table as a Structures/DebugInfo containing information about the function you passed. Can return nil if the stack level didn't point to a valid stack frame.
---@nodiscard
function debug.getinfo(thread, f, what) end
